# Si se quiere maximizar se debe de poner un signo menos a la función objetivo

# Ejercicio 

Minimice la siguiente función 

$f(x) = x^2$

In [91]:
import numpy as np
from pyswarm import pso
from sympy import *

In [14]:
def f(x):
    x1=x[0]
    return x1**2

In [26]:
lb=[-100000]
ub=[100000]
pso(f,lb,ub)

Stopping search: Swarm best objective change less than 1e-08


(array([-2.84827434e-05]), 8.112666695605066e-10)

# Ejercicio


Minimice la siguiente función 

$$f(x) = x^2$$

sujeta a la restricción

$$ g(x) = x \geq 5$$

In [25]:
def f(x):
    x1=x[0]
    return x1**2

In [33]:
def g(x):
    x1=x[0]
    return [x-5]

In [34]:
lb=[-100000]
ub=[100000]
pso(f,lb,ub,f_ieqcons = g)

Stopping search: Swarm best position change less than 1e-08


(array([5.0000001]), 25.00000096983894)

# Ejercicio

Una caja rectangular sin tapa se hace con $12 m^2$ de cartón.

Calcule el volumen máximo de esta caja.

Solucion:

Sean $x, y$ y $z$ el largo, el ancho
y la altura, respectivamente, de la caja medidos en metros. Buscamos maximizar

$$V=xyz $$

sujeta a la restricción

$$g(x,y,z) = 2xz + 2yz + xy = 12$$

In [82]:
def V(w):
    x=w[0]
    y=w[1]
    z=w[2]
    return -x*y*z
def g(w):
    x=w[0]
    y=w[1]
    z=w[2]
    return [(2*x*z+2*y*z+x*y-12)*-1]

In [89]:
lb=[0,0,0]
ub=[10,10,10]
pso(V,lb,ub,f_ieqcons =g,maxiter=300)

Stopping search: Swarm best position change less than 1e-08


(array([2.11079031, 2.16615654, 0.86833947]), -3.970310500337101)

# Ejercicio

Un agricultor tiene $2 400$ metros de material y quiere construir una barda para
cercar un campo rectangular que bordea un río recto, de modo que no necesita barda a
lo largo del río. 

¿Cuáles son las dimensiones que debe tener el campo para encerrar el
área más grande?

### Solución

- Queremos maximizar el área $A$ del rectángulo.

$$A(x,y) = xy $$

Ademas tenemos una restriccion, utilizamos la información dada de que la longitud total de la barda es $2400$ metros

$$2x + y = 2400 $$

In [90]:
def A(w):
    x=w[0]
    y=w[1]
    return -x*y
def g(w):
    x=w[0]
    y=w[1]
    return [(2*x+y-2400)*-1]
lb=[0,0]
ub=[2000,2000]
pso(A,lb,ub,f_ieqcons=g,maxiter=300)

Stopping search: Swarm best position change less than 1e-08


(array([ 601.60140411, 1196.79719168]), -719994.8709493594)

# Ejercicio

Se va un fabricar una lata que ha de contener $1 L$ de aceite. Encuentre
las dimensiones que debe tener la lata de manera que minimicen el costo del metal para fabricarla.

De esta manera, el área superficial es
$$A(r,h) = 2\pi r^2 + 2\pi r h  $$

El volumen está dado como $1 L$, que tomamos como $1000$ $cm^3$

$$\pi r^2h=1000 $$



In [94]:
def A(w):
    r=w[0]
    h=w[1]
    return 2*pi*r**2+2*pi*r*h
def g(w):
    r=w[0]
    h=w[1]
    return [pi*r**2*h-1000]
lb=[0,0]
ub=[1000,1000]
pso(A,lb,ub,f_ieqcons=g,maxiter=300)

Stopping search: Swarm best position change less than 1e-08


(array([ 5.4320909 , 10.78738227]), 176.21130546403*pi)